name: Deploy API Gateway

on:
  push:
    branches:
      - main   # runs when you push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Copy JAR to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "target/EntryPoint_Gateway-0.0.1-SNAPSHOT.jar"
          target: "/root/microservices/api-gateway/"

      - name: Restart API Gateway Service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/microservices/api-gateway
            pkill -f "EntryPoint_Gateway-0.0.1-SNAPSHOT.jar" || true
            nohup java -jar EntryPoint_Gateway-0.0.1-SNAPSHOT.jar > gateway.log 2>&1 &
