name: Deploy API Gateway

on:
  push:
    branches:  master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # ✅ Add this step before SCP
    - name: Test SSH to VPS
      run: |
        echo "${{ secrets.VPS_SSH_KEY }}" > test_key
        chmod 600 test_key
        ssh -i test_key -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo Success"

    - name: Copy JAR to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: |
          ${{ secrets.VPS_SSH_KEY }}
        source: "target/EntryPoint_Gateway-0.0.1-SNAPSHOT.jar"
        target: "/root/microservices/api-gateway/"
        port: 22
